### ISSUE TITLE
(IF-NEEDED) Transition the build logic to account for browsers that don't support `Blocking-WebRequest`.

### ISSUE THREAD

**Issue by whizzzkid** [ipfs-shipyard/ipfs-companion#1154]
Parent Issue: https://github.com/ipfs/ipfs-companion/issues/1152
Blocked By: https://github.com/ipfs/ipfs-companion/issues/1153

**This only applies if the spike(#1153) fails.**

ETA: 2023-03-30

```[tasklist]
### Tasks
- [ ] Refactor code to make blocking handler logic pluggable.
- [ ] Implement importing of relevant logic based on target env.
- [ ] Validate changes.
- [ ] Devise a testing strategy for `declarativeNetRequest` API.
```

**Comment by SgtPooki** [comment]
The initial tasks in this issue should be fairly trivial given webpack and the existing build logic.

**Comment by lidel** [comment]
Before you sink too much time into this, double-check if we need to have a separate webpack build, and not just different Manifest for Firefox and Chromium (which we already have).  

Afaik as long manifest if ok, you can do detection at runtime, like we do in https://github.com/ipfs/ipfs-companion/blob/main/add-on/src/lib/runtime-checks.js 

In the past, every time we did anything fancy in webpack in companion it was a maintenance hell (libraries breaking APIs after few months/years, entire webpack  deprecating apis and forcing ecosystem to migrate, just bunch of useless work to keep functionalkity going AND have up-to-date depoendencies
).
