### ISSUE TITLE
[deferred] Observe WebRequests and populate LFU Cache

### ISSUE THREAD

**Issue by whizzzkid** [ipfs-shipyard/ipfs-companion#1155]
Parent Issue: https://github.com/ipfs/ipfs-companion/issues/1152

ETA: 2023-05-12

```[tasklist]
### Tasks
- [x] Observe webRequests via the non-blocking API
- [ ] Implement LFU  maintain list of LFU URLs that can be serviced by companion.
- [ ] Validate LFU thresholds to have sufficient content that exceeds the blockable requests.
```

## Discussion Notes:

- [ ] Explore LRFU Cache
- [ ] Explore [2Q Cache](https://www.npmjs.com/package/2q-cache)

**Comment by BigLep** [comment]
@whizzzkid : I'm wondering if we're over complicating this.  A couple of thoughts:
1. We can store 5k regexes right?  Do we have a sense of whether 5k+ domains even have "IPFS support"?  Related, over the course of someone's browsing session, how many unique domains (regardless if they have "IPFS support") does one have?  My guess is that 5k is plenty big enough.  Before we do work here, lets just get a metric on how big we find this to be in practice.
2. Once the 5k limit is hit, what happens when you try to add another regex?  Do you get an error?  Do you have to choose what regex to evict so thee is space for the new regex you want to add?

**Comment by BigLep** [comment]
Ok, got it.  It's good to know we get an error and thus have a metric we can report.

I don't think we should put energy on being fancy for now.  I think we should ship and then can improve this later if we see the need in the metrics.
