### ISSUE TITLE
Implement MV3 Checklist

### ISSUE THREAD

**Issue by whizzzkid** [ipfs-shipyard/ipfs-companion#1169]
This issue tracks implementation of: https://developer.chrome.com/docs/extensions/mv3/mv3-migration/

ETA: 2023-03-30

### Tasks
- [x] Migrate `manifest_version: 2` -> `manifest_version: 3`
- [x] Migrate `background.page` -> `background.service_worker`
- [x] https://github.com/ipfs/ipfs-companion/issues/1171
  - [x] Implement a new build step to build `service_worker.js` instead of `background.html`
  - [x] Remove instances of `window`.
  - [x] Migrate instances of `localStorage` -> `browser.storage`.
- [x] Migrate `web_accessible_resources` -> url specific resources.
- [x] Migrate `content_security_policy` -> `content_security_policy.extension_pages`
- [x] Migrate `browser_action`
- [x] Migrate away from `eval`
- [x] Migrate `chrome.contextMenus.create` -> `chrome.contextMenus.onClicked`
- [x] `fetch` with cors enabled: https://github.com/ipfs/kubo/pull/8690
- [x] redirects with `Access-Control-Allow-Origin`: https://github.com/ipfs/kubo/issues/9728
