### ISSUE TITLE
Automatic Config Migration MV2 -> Mv3

### ISSUE THREAD

**Issue by whizzzkid** [ipfs-shipyard/ipfs-companion#1226]
When Mv2 companion will be replaced with mv3 companion, the configs will not automatically migrate. The reason is the `serviceWorker` context does not allow access to mv2 `localStorage` (html5 storage) instead the new way is `chrome.storage.local` (storage specifically designed for extensions) which will set the configs to default on upgrade.

To make the transition smoother for current users:

```[tasklist]
### Tasks
- [x] Show an upgraded screen on the first upgrade from MV2 -> MV3 (this is not liked by our users and was removed in https://github.com/ipfs/ipfs-companion/issues/933)
- [x] Make the screen show migration info or just a notice that it's a one time thing.
- [x] Use the window context from this upgrade screen to access `window.localStorage`
- [x] Post this to the background service worker and save it in `chrome.storage.sync` or `chrome.storage.local`
- [ ] Validate and write tests.
```
