### ISSUE TITLE
Implement metrics collection.

### ISSUE THREAD

**Issue by whizzzkid** [ipfs-shipyard/ipfs-companion#1227]
Metrics cannot be collected from the service worker, it happens in the window context only for now.

```[tasklist]
### Tasks
- [x] Implement minimal API to send metrics to countly using fetch in serviceWorker context.
- [x] Collect URLs intercepted and served using the routes.
- [x] refactor frontend pages to utilize this common channel to push metrics.
- [x] Revert https://github.com/ipfs/ipfs-companion/pull/1172
```
