### ISSUE TITLE
Implement Rule Management View on The Options Page.

### ISSUE THREAD

**Issue by whizzzkid** [ipfs-shipyard/ipfs-companion#1231]
```[tasklist]
### Tasks
- [x] On the options page, add a view to visualize all active rules
- [x] Add option to remove individual rules
- [x] Add option to reset all rules.
```
