### ISSUE TITLE
Migrate all Redirection tests with MV3 implementations.

### ISSUE THREAD

**Issue by whizzzkid** [ipfs-shipyard/ipfs-companion#1235]
```[tasklist]
### Tasks
- [x] Migrate test/functional/lib/ipfs-request-dnslink.test.js
- [x] Migrate test/functional/lib/ipfs-request-gateway-redirect.test.js
- [x] Migrate test/functional/lib/ipfs-request-protocol-handlers.test.js
- [x] Optional test/functional/lib/ipfs-request-workarounds.test.js
```
