### ISSUE TITLE
More strict MV3 rules for path and subdomain gateways 

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#1253]
URL like `https://ipfs.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR` produces rules like
```
origin: '^https?\\:\\/\\/ipfs\\.io',
destination: 'http://127.0.0.1:8080'
```

The MV3 rules created by ipfs-companion beta 3.0.0.1114 for a public path or subdomain gateway should be for specific namespace like /ipfs or /ipns, never for the entire origin. Redirecting entire origin should happen only for DNSLink websites.

For public path and subdomain gateways we don't want to have a situation where we break delegated routing because companion hijacked `/routing/v1` endpoint, or some other `/foo`  service endpoint that domain owner decided to expose on the same hostname,
```[tasklist]
### Tasks
- [x] Make rules less greedy and explict to the namespace.
- [x] Add unit tests for DEFAULT_LOCAL_RULES https://github.com/ipfs/ipfs-companion/pull/1236#discussion_r1283178344
- [x] Don't break dev environments: https://github.com/ipfs/ipfs-companion/pull/1236#discussion_r1283180376
- [ ] https://github.com/ipfs/ipfs-companion/issues/1254
- [ ] https://github.com/ipfs/ipfs-companion/issues/1255
```

**Comment by lidel** [comment]
My suggestion would be to 
- remove special-handling of Fleek (even if it is "generic" magical detection of CIDs in domains that do not have namespace label)
- reach out to Fleek and ask them to follow the specs (linked below) and use  `{cid}.ipfs.on.fleek.co` instead

We have subdomain convention for a reason, it requires namespace label after the CID to remove surface for false-positives (confusing with ipns, peerid, or uses outside content-addressed paths):
- https://specs.ipfs.tech/http-gateways/subdomain-gateway/
- https://docs.ipfs.tech/how-to/address-ipfs-on-web/#subdomain-gateway
