### ISSUE TITLE
UX improvements for sharing local files

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#342]
Something that deserves own mini-journey:  sharing local files via IPFS

It is a silent one, but honestly this is a "killer feature" when it comes to convenience. 
 
What we have right now:

- "Share local files via IPFS" in Companion's browser action menu opens the upload tab
- support for drag&drop ✨  (latest beta)
- preload at public gateway
- ugly URL: produces raw CID 

Some ideas on how to make it a better experience:

- [x] Display IPFS addresses instead of opening uploaded file (tracked in #423)
  - [x] Partially delivered by directory wrapping (PR #479)
- [x] Save all uploads to MFS (`ipfs.files`) (tracked in #415)
-  [x] Progress indicator (tracked in #295)
-  [x] Keeping original filename in URL by wrapping a file in a directory  (tracked in https://github.com/ipfs-shipyard/ipfs-companion/issues/349, added in PR #479)
-  [x] Sharing multiple files  (added in PR #479)
-  [ ] Sharing directories  (tracked in #396)
-  [ ] Optional symmetric encryption (catering to less savvy users)  (https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/53)
- [x] Handle / fix crash when dropping a big file #464
- [ ] Feature: option to automatically copy url when adding to ipfs #576
- [ ] Support local camera or external services 
  - see https://uppy.io

### Related 

- Design aspect of "Sharing" is currently tracked in https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/34

**Comment by jessicaschilling** [comment]
Closing this one, since its remaining components are tracked in their own issues.
