### ISSUE TITLE
Release Checklist for v2.2.0

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#347]
We've been producing betas for a while. I feel there should be a new release at the beginning of a new year with a main goal to deliver recent UI improvements. 

Let's go with a solid checklist this time. It may grow, as I want to create a template for future re-use:

## New Features

- [x] `window.ipfs` (https://github.com/ipfs-shipyard/ipfs-companion/issues/330)
  - [x] Isolate ACL for window.ipfs on IPFS paths (assume HTTP gateway) (#375)
  - [x] Custom dialog for window.ipfs ACLs (make it work under Firefox) (#377)
  - [x] Decide if window.ipfs should be injected into all_frames (#392)

## Pre-Release Checklist

- [x] all tests pass
  - [x] manual check: Firefox for Android
- [x] locales
  - [x] sync translations with [Crowdin](https://crowdin.com/project/ipfs-companion)
  - [x] resolve any issues / questions raised at [Crowdin](https://crowdin.com/project/ipfs-companion)
- [x] verify that `ipfs-postmsg-proxy`,  `ipfs` and `ipfs-api` deps are  up to date
- [x] close [known bugs](https://github.com/ipfs-shipyard/ipfs-companion/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22upstream+bug%22%2Cbug) that are not blocked by something external 
  - [x] error while removing IPFS Pin (https://github.com/ipfs-shipyard/ipfs-companion/issues/338)
  - [x] investigate odd behavior when removing pin under Firefox (https://github.com/ipfs-shipyard/ipfs-companion/issues/338)
  - [x] investigate random error on Android, when running in background (~ once a day)
  - [x] window.ipfs injected after page loaded #362 
  - [x] Daemon is off but redirect is still enabled #373
  - [ ] Restarting ipfs daemon sometimes freezes the browser #360
  - [x] ReferenceError: can't access lexical declaration `offlinePeerCount' before initialization #378
  - [x] Some locales do not load #434
- [x] before release, tag 'release candidate' for users to test against
  - if bugs are found/fixed, do another release candidate

## Post-Release

- [x] do the reproducible build dance
- [x] write Release Notes
- [x] publish
  - [x] AMO 
  - [x] Chrome Store
- [x] write a blogpost at blog.ipfs.io (https://github.com/ipfs-shipyard/ipfs-companion/issues/344)
- [x] save this checklist as a template for future reuse :)

**Comment by lidel** [comment]
[v2.2.0](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.2.0) got released, blog post: https://github.com/ipfs/blog/pull/156
