### ISSUE TITLE
Detect IPFS Desktop and Provide Additional Node Controls

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#350]
Some of user journeys introduce presence of [IPFS Desktop](https://github.com/ipfs-shipyard/ipfs-desktop) (previously known as Station). It is a standalone Electron app that can do a lot more than we can do in WebExtension.

WebExtensions provide [Native messaging API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging), which may be used for communication with external executable installed on user's system. 

## TL;DR
The idea is to detect presence of IPFS Desktop and provide user with additional controls.

MVP: show controls for starting/stopping go-ipfs daemon

## Tasks

- [ ] Research  if APIs in Chrome and Firefox are close enough that we can maintain single codebase 🤞 
- [ ] Add necessary files to IPFS Desktop installer
- [ ] Add native messaging support to Companion
- [ ] Add controls for starting / stopping daemon installed with IPFS Desktop
- [ ] Documentation explaining how to add other hooks/controls over Native messaging bridge

## References
- ipfs/in-web-browsers: [IPFS node info and node controls](https://github.com/ipfs/in-web-browsers/issues/12)
- PoC @ https://github.com/whyrusleeping/ipfs-webext
- [Native messaging API Docs @ Mozilla](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging)
