### ISSUE TITLE
Switch to latest js-ipfs-api for /api/v0/dns lookups

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#357]
### Background

- https://github.com/ipfs/js-ipfs-api/issues/501
- https://github.com/ipfs/js-ipfs-api/pull/665  (right now we send XHR manually)

###  Tasks

- [ ] [Confirm](https://github.com/ipfs/js-ipfs-api/issues/501#issuecomment-358056476) that implementation in js-ipfs-api [v17.3.0](https://github.com/ipfs/js-ipfs-api/releases/tag/v17.3.0) is ready for use
- [ ] Update to the latest js-ipfs-api 
- [ ] As a part of this task we should update option description and inform user that if DNSLINK lookup  is enabled and public gateway is set as an active one, browser extension will send host names of every visited site to it (privacy leakage).

**Comment by ef3n9r98** [comment]
Hey @lidel, if this issue is still open, is there a willingness to pay a dev a bounty to fix it?
