### ISSUE TITLE
Support and reuse ipfs.types and ipfs.util

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#444]
## Background 

I requested something similar some time ago (), and it just landed :rocket: 
Since last week a set of data types and utils is being exposed directly from the IPFS instance under `ipfs.types` and `ipfs.util`:

- [`ipfs.types.Buffer`](https://www.npmjs.com/package/buffer)
- [`ipfs.types.PeerId`](https://github.com/libp2p/js-peer-id)
- [`ipfs.types.PeerInfo`](https://github.com/libp2p/js-peer-info)
- [`ipfs.types.multiaddr`](https://github.com/multiformats/js-multiaddr)
- [`ipfs.types.multibase`](https://github.com/multiformats/multibase)
- [`ipfs.types.multihash`](https://github.com/multiformats/js-multihash)
- [`ipfs.types.CID`](https://github.com/ipld/js-cid)
- [`ipfs.types.dagPB`](https://github.com/ipld/js-ipld-dag-pb)
- [`ipfs.types.dagCBOR`](https://github.com/ipld/js-ipld-dag-cbor)
- [`ipfs.util.crypto`](https://github.com/libp2p/js-libp2p-crypto)
- [`ipfs.util.isIPFS`](https://github.com/ipfs-shipyard/is-ipfs)

Source: https://github.com/ipfs/interface-ipfs-core/pull/252, [SPEC/TYPES.md](https://github.com/ipfs/interface-ipfs-core/blob/0cf94b852ecf22e897ee39f2a9c5250825384950/SPEC/TYPES.md), [SPEC/UTIL.md](https://github.com/ipfs/interface-ipfs-core/blob/0cf94b852ecf22e897ee39f2a9c5250825384950/SPEC/UTIL.md)

### Availability Status

- [x] js-ipfs-api ([v20.0.0](https://github.com/ipfs/js-ipfs-api/releases/tag/v20.0.0)): , https://github.com/ipfs/js-ipfs-api/pull/732
- [ ] js-ipfs (**waiting for release**): https://github.com/ipfs/js-ipfs/pull/1297

## Tasks

- [ ] switch to js-ipfs-api and js-ipfs with support for these endpoints
- [ ] switch to bundled types and utils 
- [ ] remove duplicate dependencies
- [ ] expose `ipfs.types` and `ipfs.util` under `windows.ipfs` (if feasible)

**Comment by lidel** [comment]
Closing due to https://github.com/ipfs-shipyard/ipfs-companion/issues/589#issuecomment-712356448
