### ISSUE TITLE
New UI for Backend Control

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#491]
### Tasks

- [x] define what is missing and what elements need to be added to UI
- [x] design drop-down and toggle (browser_action)
- [ ] design backend list editor (Preferences) – see notes below
- [ ] implement changes
  - [x] move node type switch to Preferences
  - [x] ON/OFF toggle  https://github.com/ipfs-shipyard/ipfs-companion/issues/491#issuecomment-398828326
  - [ ] backend list editor (Preferences)
- [ ] migrate existing settings to a new item in "backend list"
- [ ] close all issues in [related milestone](https://github.com/ipfs-shipyard/ipfs-companion/milestone/14)

-----

### Background

<details>
  <summary>Click to expand historical notes on why this change was proposed</summary>

Right now we have a simple toggle between _Embedded_ node (browserified js-ipfs) and _External_ node (usually go-ipfs at IP and port [defined in Preferences](https://user-images.githubusercontent.com/157609/40840535-6c2136cc-65a7-11e8-83af-003737ce4ab9.png), accessed over HTTP API):

> ![screenshot_7](https://user-images.githubusercontent.com/157609/40840515-52ca52d0-65a7-11e8-98c7-ead6fe248600.png)

### Limitations
- No obvious one-click to "enable/disable" what IPFS Companion does. 
    - Multiple users raised the need for "off" switch.
    - Removal of all redirects of IPFS paths and `window.ipfs` object during web development requires going over multiple checkboxes in Preferences or disabling the entire extension via Addon Manager (was the case when troubleshooting [CORS bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=1450965)).
   - No clear indication when "power-user ipfs mode" (with local node, API and `window.ipfs`)  is enabled, and when  "vanilla public" (no API) gateway is used. This makes troubleshooting of various issues harder than necessary.
- Switching between "backend" different nodes is a chore, one needs to change URLs in _Preferences_  each time.
   - Users raised a need for making this easier, namely having a predefined list of backends that one can pick. MetaMask network-picker was given as an example of what is missing in Companion: 
      > ![screenshot](https://user-images.githubusercontent.com/157609/40844298-d9736a0e-65b3-11e8-95fb-c1e89bf4d93d.png)
- _Embedded_ node will have a different meaning in environments where js-ipfs is replaced with orchestrated instance of go-ipfs. Still, we should be able to make it possible to use js-ipfs in those environments, if user choose to do so.

</details>

# Proposed UI Changes

Let's replace two-state toggle with global ON/OFF toggle + a drop-down list that enables selection from multiple available backends:

## Browser Action Popup

-  collapsed - mockup:
   >  ![screenshot_9](https://user-images.githubusercontent.com/157609/40841564-32289876-65ab-11e8-8d58-46a0ca609f2e.png)  
- expanded - mockup:
  > ![screenshot_11](https://user-images.githubusercontent.com/157609/40845971-872c689a-65b8-11e8-8d26-e5f35a5fe39e.png)
  > ( just a sketch, some design work needs to happen here to use space more efficiently)
- [x] ON/OFF toggle will be one-click switch for: ([IMPLEMENTED](https://github.com/ipfs-shipyard/ipfs-companion/issues/491#issuecomment-398828326))
   - API status polling
   - redirect of IPFS paths to custom gateway (if enabled in preferences)
   - spawning/destroying js-ipfs instance (if selected as a current backend)
   - exposing API as `window.ipfs` (if enabled in preferences)
   - making possible to pick different backend via drop-down menu (see below)
- [ ] Drop-down list will include available backends that control:
  - which API is used for uploads, polled, exposed in status section and under `window.ipfs`
  - which HTTP gateway is used for redirect (if enabled in preferences)

## Simplified Backend List on Preferences Screen

Preferences screen should have an UI for adding/removing  "IPFS Backends" that appear in the dropdown list rendered in `browser_action`.

-  Preferences UI: replace  "node type" and "custom and public gateway" forms with a single  list of  backends
  - Currently active Gateway/API ports will be hidden from Preferences screen and be solely based on which backend node is picked by the user in browser action popup menu
  - user-defined backends can be added/removed from the list
  - "embedded" js-ipfs is implicit, always present, cant be removed
  - each entry has attributes:
    -  "label"
    - "API" and "Gateway" URLs
     (why both need to be defined? Gateway port can be fetched from API port, but it is not 100% safe as people are known to put it behind reverse-proxy such as nginx, and we want to use one list for Gateway-only backends)
    - a checkbox "public gateway without API" that disables API field and marks backend for use as "public gateway"
    - a checkbox "embedded, no HTTP gateway" that disables HTTP Gateway field (afaik there will be only one example: embedded js-ipfs node, so this checkbox may be a hidden flag, eg in "metadata" field below)
    -  "metadata" – hidden, used for storing additional flags (eg. making sure default public or embedded node can't be removed)
    -  "custom headers" – an option to define custom headers per backend (https://github.com/ipfs-shipyard/ipfs-companion/issues/538#issuecomment-407226626)
   - "external" nodes are loaded from [storage.local](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local). 
  - If the list is empty, an item with current "localhost" defaults is added automatically when extension starts for the first time.
- Future / Nice to haves
  - A way to dynamically import list of public gateways  (eg. [this one](https://github.com/ipfs/public-gateway-checker/blob/master/gateways.json)) 

   
-----

cc @olizilla @akrych 

Thoughts?

**Comment by lidel** [comment]
@olizilla I like the idea, hovewer something to note is that we already display info about currently used API and Gateway in the bottom "status" section. 

- To avoid content duplication we may just add a clickable "change" action to the status section that opens _Preferences_. It could be as simple as an icon: :wrench:  or :gear:   next to "gateway" and "api" or something like that.  
- Existing toggle could remain in the same place, but its meaning would simply change from Embedded/External to Enabled/Disabled.  
- We may consider moving  entire status section above menu items, making it one with "heartbeat" icon and toggle. 

- Just like in WebUI, we should avoid use of "on hover" for key features, as it does not work on touch devices (Firefox for Android). The "change" action should be always visible.

**Comment by lidel** [comment]
### Activate / Suspend Toggle

First step was to move "node type toggle" to _Preferences_ and introduce a global "on/off" toggle that activates/suspends all IPFS integrations. Details can be found in PR #500.

It just got merged and released to Beta in [v2.3.1.9890](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.3.1.9890) :rocket: 

So far the UI moves into more calm, less cluttered direction:

![peek 2018-06-20 18-45](https://user-images.githubusercontent.com/157609/41672413-279cee84-74ba-11e8-9145-1e7de4c308f1.gif)

### Next

My initial thoughts on how to introduce "backed selector" into this minimal UI:
- UI should look the same, but enable user to switch to different backend without going to _Preferences_
   - A)  drop-down indicator  (a triange?) on the right of "API" status field
   - B) add third icon that  onclick replaces status area with bigger backend selector
   - C) ?

**Comment by olizilla** [comment]
That could work, but the extension already looks like a drop down menu, and a drop-down in a drop-down isn't ideal.

I'd start with a full page for it and figure our all the info we need to get across and the UI for adding new backends, and give the user access to it as a menu option. We can figure out the "quick change" selector once that is place.

**Comment by lidel** [comment]
Gist of feature request from https://github.com/ipfs-shipyard/ipfs-companion/issues/591:
- When adding a new backend to the list it should be enough to enter API port by itself 
- Gateway port should be read from API by default, with an opt-in option to override it per backend 
  (for custom setups where user tunels the port etc)

**Comment by hsanjuan** [comment]
I noticed the setting `Redirect to Custom Gateway` is a bit confusing right now because the local gateway is defined as `Preferred` so you would think it's used by default already.

I'm not sure what's the best way to improve it but it's a weird setting because it flips itself by toggling the public gateway from the main dropdown, and also automatically depending on local daemon' s availability. Perhaps `Automatically use custom gateway when available` would be a better config option, and leave the manual switching for the dropdown menu items.

**Comment by lidel** [comment]
- `Redirect to Custom Gateway` will be moved from menu item to a quick toggle icon in https://github.com/ipfs-shipyard/ipfs-companion/pull/687

- `Drop-down list with available backends that control` in main popup menu did not happen yet, but we started discussing revamping entire menu in https://github.com/ipfs-shipyard/ipfs-companion/issues/689 (but I believe we will add backend switcher on the Preferences screen first)

**Comment by jessicaschilling** [comment]
Closing in favor of https://github.com/ipfs-shipyard/ipfs-companion/issues/689.
