### ISSUE TITLE
webextension-polyfill v0.3.0 

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#540]
## Background 

Chrome not support promise-based `browser.*` namespace, only callback-based `chrome.*`.
We use `webextension-polyfill` to have `browser.*`.  in Chrome and run the same code as in Firefox.
Historically we did not update to 0.2.1 as it introduced some regressions in our use cases (details below), and we want to play the upgrade extra safe, as it is the key dependency for running in Chrome. 

## Tasks

- [x] switch to v0.3.1 in a feature branch
- [x] check if there are no regressions  in Chrome 
    - AFAIK historically things related to clipboard did not work with  – find and revisit those old issues for more context: https://github.com/mozilla/webextension-polyfill/issues/70
    - perhaps now that we have separate build targets we can change `generic` bundle to work v0.3.1 
- [x] check if v0.3.1 help with Edge (#353)
   - not yet, upstream PR is still open
- [x] make the switch or document what is missing

Ref.
- https://github.com/mozilla/webextension-polyfill/releases/tag/0.3.0
