### ISSUE TITLE
Embedded JS-IPFS in Brave

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#716]
> This issue tracks remaining work around embedded js-ipfs running in ipfs-companion  in Brave with access to `chrome.sockets` APIs. For more context, see:
> - Option (B) from notes on bringing IPFS to Brave in 2019 
    (https://github.com/brave/brave-browser/issues/819#issuecomment-456039555))
> - Support chrome.sockets.* APIs (https://github.com/ipfs-shipyard/ipfs-companion/issues/664)
> - Old issues: https://github.com/ipfs/in-web-browsers/issues/64, https://github.com/ipfs-shipyard/ipfs-companion/issues/312

## High Level Goals

- Leveling up js-ipfs to match go-ipfs in features relevant to in web browser uses
- Brave users can use IPFS with Companion alone, without installing go-ipfs or ipfs-desktop
- IPFS nodes in Brave can discover each other on the same network and exchange data in p2p fashion

## Kanban Board

- https://github.com/ipfs-shipyard/ipfs-companion/projects/4

## How to opt-in

Stable release of IPFS Companion can be enabled via Brave Settings (`chrome://settings/extensions`):

> ![2019-09-20--14-43-17](https://user-images.githubusercontent.com/157609/65327738-0458c200-dbb5-11e9-95d5-5393591388f6.png)

By default, it works like regular ipfs-companion and  `External` node is used by default, assuming user has [go-ipfs](https://github.com/ipfs/go-ipfs#go-ipfs) or [IPFS Desktop](https://github.com/ipfs-shipyard/ipfs-desktop#ipfs-desktop) installed and running.

Brave users can opt-in and try `Embedded + chrome.sockets` (see [/docs/node-types](https://github.com/ipfs-shipyard/ipfs-companion/blob/master/docs/node-types.md) for more details)

> ![2019-09-20--14-44-37](https://user-images.githubusercontent.com/157609/65327907-66192c00-dbb5-11e9-962f-9b5cd122572f.png)

> ![2019-09-20--14-45-06](https://user-images.githubusercontent.com/157609/65327962-7fba7380-dbb5-11e9-954b-6a18136eef60.png)

# TODO

## :art:  UX

* [ ] UI for changing Gateway port
  - Right now its just raw JSON with js-ipfs config
* [x] Redirect to embedded Gateway
* [x] New embedded node type exists (`embedded:chromesockets`)
* [x] Companion UI is aware of embedded Gateway (https://github.com/ipfs-shipyard/ipfs-companion/issues/664#issuecomment-481697875)
* [x] Play nice with go-ipfs and js-ipfs daemons (https://github.com/ipfs-shipyard/ipfs-companion/issues/664#issuecomment-481697875)
  - [x] user can switch between embedded (default in Brave) and external IPFS nodes
  - [x] use custom ports by default
* [ ] Post-install welcome screen enables user to start IPFS with one click
  * [ ] Add option to start embedded js-ipfs 
  * [ ] See if we able to make it useful on Android as well
* [ ] Brave detects URLs from embedded gateway and displays them as `ipfs://` and `ipns://` 
  - Ideally, along with Origin isolation
  - UX tracked in https://github.com/brave/brave-browser/issues/5218

##  :electric_plug:  chrome.sockets 

* [x] feature-detection for `chrome.sockets` (https://github.com/ipfs-shipyard/ipfs-companion/issues/664)
  - [x] the same package should run on Google Chrome and Brave, `chrome.sockets` should enable additional powers at runtime
- [x] Brave overrides Manifest on install from Chrome Web Store to add `sockets` section

## :globe_with_meridians:   Embedded HTTP Gateway

- [x] Companion can use HTTP gateway provided by embedded JS-IPFS node (https://github.com/ipfs-shipyard/ipfs-companion/issues/664#issuecomment-479535264)
  - [x] Decouple HTTP Servers from cli/commands/daemon (https://github.com/ipfs/js-ipfs/pull/1950)
- [x] Web UI loads and can be opened from Companion's main menu (https://github.com/ipfs-shipyard/ipfs-companion/issues/664#issuecomment-481697875)
- [ ] HTTP Responses are valid
  - [x] streaming (https://github.com/ipfs/js-ipfs/pull/1989)
  - [x] content-type sniffing (https://github.com/ipfs/js-ipfs/pull/1989)
  - [x] missing `last-modified` (https://github.com/ipfs/js-ipfs/pull/1989)
  - [x] support `if-none-match` and `304 Not Modified` (https://github.com/ipfs/js-ipfs/pull/1989)
  - [x] support `?filename` and `Content-Disposition` (https://github.com/ipfs/js-ipfs/pull/1989)
  - [x] range requests via video player (https://github.com/ipfs/js-ipfs/pull/1989)
  - [ ] Check usual suspects from https://github.com/ipfs/in-web-browsers/issues/132
- [x] **DNSLink websites** (e.g. `/ipns/docs.ipfs.io/`) are not supported by js-ipfs
  - [x] upstream fix https://github.com/ipfs/js-ipfs/issues/1918
- [x] **HAMT-sharded directories,** eg. `/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/` do not work with js-ipfs 
   - tracked upstream in https://github.com/ipfs/js-ipfs/issues/1963
- [ ] HTTP Proxy mode is supported by js-ipfs and ipfs-companion (https://github.com/ipfs/js-ipfs/issues/1877)
  - this is "nice to have" – low priority unless go-ipfs ships with it
- [ ] `...` in directory listing points at current directory instead of its parent
- [ ] Broken bandwidth graph in Web UI (https://github.com/ipfs-shipyard/ipfs-webui/issues/1012)
- [x] Unicode in paths works (eg `/ipns/tr.wikipedia-on-ipfs.org/wiki/Venüs.html`)

## :spider_web:  Local Discovery and UDP/TCP Transports

* [x] Embedded JS IPFS node is using P2P Transport over [`chrome.sockets.tcp`](https://developer.chrome.com/apps/sockets_tcp)  and [`chrome.sockets.tcpServer`](https://developer.chrome.com/apps/sockets_tcpServer)) 
  - [x] connecting to other peers
  - [x] accepting incoming connections
    - [x] discover own IP ([webrtc-ips](https://www.npmjs.com/package/webrtc-ips))
    - [ ] discover all IPs [`chrome.system.network.getNetworkInterfaces`](https://developer.chrome.com/apps/system_network) ?
* [ ] Embedded JS IPFS node performs DNS-based Local Discovery (https://github.com/ipfs/in-web-browsers/issues/45)
  - [chrome.mdns](https://developer.chrome.com/apps/mdns) implements [this dead spec](http://www.w3.org/TR/discovery-api/) and is not useful for our use case, but we should  be able to implement working doscovery on top of [`chrome.sockets.udp`](https://developer.chrome.com/apps/sockets_udp) 
  - [ ] short-term interop with go-ipfs: https://github.com/libp2p/js-libp2p-mdns/pull/80/
    - [x] discover go-ipfs 
    - [ ] broadcast own TCP multiaddr (tracked in https://github.com/ipfs-shipyard/ipfs-companion/issues/758)
  - [ ] long-term interop (new spec): https://github.com/libp2p/specs/pull/80

## :zap: Performance

- [ ] :male_detective:  **Finding/loading content** 
  - noticeable especially when preload nodes are under load and slow to respond
  - may just go away when we add p2p transport that can interop with go nodes (assuming DHT issues are addressed by then)
  - for now, we may mitigate this by enabling DHT with autorelay, or doing preloads and delegated routing:
    - [x] preload things requested via gateway (https://github.com/ipfs/js-ipfs/issues/2335)
    - [x] delegated routing: https://github.com/ipfs/js-ipfs/issues/2155
      - [x] unable to enable :upside_down_face:  https://github.com/ipfs/js-ipfs/pull/2253/
      - [x] blocked due to request flood: https://github.com/libp2p/js-libp2p-delegated-content-routing/issues/12
    - [ ] Enable DHT
      - Overview of issues and why its disabled for now: https://github.com/ipfs/js-ipfs/issues/1984
      - Closest peers query is not efficient: https://github.com/libp2p/js-libp2p-kad-dht/issues/86
- [ ] UI / defaults for storage limits and GC in js-ipfs
  - js-ipfs does not have GC yet: https://github.com/ipfs/js-ipfs/pull/2022
- [ ] inspect libp2p connection manager limits
- [x] DNS lookups hit `ipfs.io/api/v0/dns`: we need to add cache to this, or support DoH (https://github.com/ipfs/js-ipfs/issues/2212) or implement  `chrome.sockets.udp*` API
  - [x] Throttling and caching implemented in https://github.com/ipfs/js-ipfs/pull/2304

**Comment by warren-bank** [comment]
What are the implications and strategy to deal with Google's announcement that Chrome Apps and its APIs (including `chrome.sockets.*`) are deprecated and will be phased out by the end of 2020?

https://blog.chromium.org/2020/01/moving-forward-from-chrome-apps.html
https://developers.chrome.com/apps/migration

**Comment by voidao** [comment]
Hi @lidel @warren-bank , any place(github repository) for trying the progress(source code)? Thanks!

**Comment by lidel** [comment]
@warren-bank  Google's decision end support for "Chrome Apps" in 2022 does not mean immediate removal of `chrome.*` APIs from the Chromium codebase, and even if that happens, other Chromium-based browsers such as Brave may decide to keep them alive for bit longer, if the maintenance cost is low enough.

Embedded js-ipfs + `chrome.sockets*` experiment is designed to be a stop-gap until we have  native support in Chromium.  Depending on how timeline of things like rust-ipfs looks like, we may look into orchestrating go-ipfs similar to what Brave does with Tor binary (before 2022 comes).

----

@voidao sources are in this repo: code responsible for initializing embedded js-ipfs  in Brave is contained within `add-on/src/lib/ipfs-client/embedded-chromesockets`

**Comment by tojin12341za** [comment]
> > This issue tracks remaining work around embedded js-ipfs running in ipfs-companion  in Brave with access to `chrome.sockets` APIs. For more context, see:
> > 
> > * Option (B) from notes on bringing IPFS to Brave in 2019
> >   ([brave/brave-browser#819 (comment)](https://github.com/brave/brave-browser/issues/819#issuecomment-456039555)))
> > * Support chrome.sockets.* APIs (#664)
> > * Old issues: [ipfs/in-web-browsers#64](https://github.com/ipfs/in-web-browsers/issues/64), #312
> 
> ## High Level Goals
> * Leveling up js-ipfs to match go-ipfs in features relevant to in web browser uses
> * Brave users can use IPFS with Companion alone, without installing go-ipfs or ipfs-desktop
> * IPFS nodes in Brave can discover each other on the same network and exchange data in p2p fashion
> 
> ## Kanban Board
> * https://github.com/ipfs-shipyard/ipfs-companion/projects/4
> 
> ## How to opt-in
> Stable release of IPFS Companion can be enabled via Brave Settings (`chrome://settings/extensions`):
> 
> > ![2019-09-20--14-43-17](https://user-images.githubusercontent.com/157609/65327738-0458c200-dbb5-11e9-95d5-5393591388f6.png)
> 
> By default, it works like regular ipfs-companion and `External` node is used by default, assuming user has [go-ipfs](https://github.com/ipfs/go-ipfs#go-ipfs) or [IPFS Desktop](https://github.com/ipfs-shipyard/ipfs-desktop#ipfs-desktop) installed and running.
> 
> Brave users can opt-in and try `Embedded + chrome.sockets` (see [/docs/node-types](https://github.com/ipfs-shipyard/ipfs-companion/blob/master/docs/node-types.md) for more details)
> 
> > ![2019-09-20--14-44-37](https://user-images.githubusercontent.com/157609/65327907-66192c00-dbb5-11e9-962f-9b5cd122572f.png)
> 
> > ![2019-09-20--14-45-06](https://user-images.githubusercontent.com/157609/65327962-7fba7380-dbb5-11e9-954b-6a18136eef60.png)
> 
> # TODO
> ## 🎨 UX
> * [ ]  UI for changing Gateway port
>   
>   * Right now its just raw JSON with js-ipfs config
> * [x]  Redirect to embedded Gateway
> * [x]  New embedded node type exists (`embedded:chromesockets`)
> * [x]  Companion UI is aware of embedded Gateway ([#664 (comment)](https://github.com/ipfs-shipyard/ipfs-companion/issues/664#issuecomment-481697875))
> * [x]  Play nice with go-ipfs and js-ipfs daemons ([#664 (comment)](https://github.com/ipfs-shipyard/ipfs-companion/issues/664#issuecomment-481697875))
>   
>   * [x]  user can switch between embedded (default in Brave) and external IPFS nodes
>   * [x]  use custom ports by default
> * [ ]  Post-install welcome screen enables user to start IPFS with one click
>   
>   * [ ]  Add option to start embedded js-ipfs
>   * [ ]  See if we able to make it useful on Android as well
> * [ ]  Brave detects URLs from embedded gateway and displays them as `ipfs://` and `ipns://`
>   
>   * Ideally, along with Origin isolation
>   * UX tracked in [brave/brave-browser#5218](https://github.com/brave/brave-browser/issues/5218)
> 
> ## 🔌 chrome.sockets
> * [x]  feature-detection for `chrome.sockets` (#664)
>   
>   * [x]  the same package should run on Google Chrome and Brave, `chrome.sockets` should enable additional powers at runtime
> 
> * [x]  Brave overrides Manifest on install from Chrome Web Store to add `sockets` section
> 
> ## 🌐 Embedded HTTP Gateway
> * [x]  Companion can use HTTP gateway provided by embedded JS-IPFS node ([#664 (comment)](https://github.com/ipfs-shipyard/ipfs-companion/issues/664#issuecomment-479535264))
>   
>   * [x]  Decouple HTTP Servers from cli/commands/daemon ([ipfs/js-ipfs#1950](https://github.com/ipfs/js-ipfs/pull/1950))
> * [x]  Web UI loads and can be opened from Companion's main menu ([#664 (comment)](https://github.com/ipfs-shipyard/ipfs-companion/issues/664#issuecomment-481697875))
> * [ ]  HTTP Responses are valid
>   
>   * [x]  streaming ([ipfs/js-ipfs#1989](https://github.com/ipfs/js-ipfs/pull/1989))
>   * [x]  content-type sniffing ([ipfs/js-ipfs#1989](https://github.com/ipfs/js-ipfs/pull/1989))
>   * [x]  missing `last-modified` ([ipfs/js-ipfs#1989](https://github.com/ipfs/js-ipfs/pull/1989))
>   * [x]  support `if-none-match` and `304 Not Modified` ([ipfs/js-ipfs#1989](https://github.com/ipfs/js-ipfs/pull/1989))
>   * [x]  support `?filename` and `Content-Disposition` ([ipfs/js-ipfs#1989](https://github.com/ipfs/js-ipfs/pull/1989))
>   * [x]  range requests via video player ([ipfs/js-ipfs#1989](https://github.com/ipfs/js-ipfs/pull/1989))
>   * [ ]  Check usual suspects from [ipfs/in-web-browsers#132](https://github.com/ipfs/in-web-browsers/issues/132)
> * [x]  **DNSLink websites** (e.g. `/ipns/docs.ipfs.io/`) are not supported by js-ipfs
>   
>   * [x]  upstream fix [ipfs/js-ipfs#1918](https://github.com/ipfs/js-ipfs/issues/1918)
> * [x]  **HAMT-sharded directories,** eg. `/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/` do not work with js-ipfs
>   
>   * tracked upstream in [ipfs/js-ipfs#1963](https://github.com/ipfs/js-ipfs/issues/1963)
> * [ ]  HTTP Proxy mode is supported by js-ipfs and ipfs-companion ([ipfs/js-ipfs#1877](https://github.com/ipfs/js-ipfs/issues/1877))
>   
>   * this is "nice to have" – low priority unless go-ipfs ships with it
> * [ ]  `...` in directory listing points at current directory instead of its parent
> * [ ]  Broken bandwidth graph in Web UI ([ipfs-shipyard/ipfs-webui#1012](https://github.com/ipfs-shipyard/ipfs-webui/issues/1012))
> * [x]  Unicode in paths works (eg `/ipns/tr.wikipedia-on-ipfs.org/wiki/Venüs.html`)
> 
> ## 🕸️ Local Discovery and UDP/TCP Transports
> * [x]  Embedded JS IPFS node is using P2P Transport over [`chrome.sockets.tcp`](https://developer.chrome.com/apps/sockets_tcp)  and [`chrome.sockets.tcpServer`](https://developer.chrome.com/apps/sockets_tcpServer))
>   
>   * [x]  connecting to other peers
>   * [x]  accepting incoming connections
>     
>     * [x]  discover own IP ([webrtc-ips](https://www.npmjs.com/package/webrtc-ips))
>     * [ ]  discover all IPs [`chrome.system.network.getNetworkInterfaces`](https://developer.chrome.com/apps/system_network) ?
> * [ ]  Embedded JS IPFS node performs DNS-based Local Discovery ([ipfs/in-web-browsers#45](https://github.com/ipfs/in-web-browsers/issues/45))
>   
>   * [chrome.mdns](https://developer.chrome.com/apps/mdns) implements [this dead spec](http://www.w3.org/TR/discovery-api/) and is not useful for our use case, but we should  be able to implement working doscovery on top of [`chrome.sockets.udp`](https://developer.chrome.com/apps/sockets_udp)
>   * [ ]  short-term interop with go-ipfs: [libp2p/js-libp2p-mdns#80](https://github.com/libp2p/js-libp2p-mdns/pull/80)
>     
>     * [x]  discover go-ipfs
>     * [ ]  broadcast own TCP multiaddr (tracked in #758)
>   * [ ]  long-term interop (new spec): [libp2p/specs#80](https://github.com/libp2p/specs/pull/80)
> 
> ## ⚡ Performance
> * [ ]  🕵️‍♂️  **Finding/loading content**
>   
>   * noticeable especially when preload nodes are under load and slow to respond
>   * may just go away when we add p2p transport that can interop with go nodes (assuming DHT issues are addressed by then)
>   * for now, we may mitigate this by enabling DHT with autorelay, or doing preloads and delegated routing:
>     
>     * [x]  preload things requested via gateway ([ipfs/js-ipfs#2335](https://github.com/ipfs/js-ipfs/issues/2335))
>     * [x]  delegated routing: [ipfs/js-ipfs#2155](https://github.com/ipfs/js-ipfs/issues/2155)
>       
>       * [x]  unable to enable 🙃  [ipfs/js-ipfs#2253](https://github.com/ipfs/js-ipfs/pull/2253)
>       * [x]  blocked due to request flood: [libp2p/js-libp2p-delegated-content-routing#12](https://github.com/libp2p/js-libp2p-delegated-content-routing/issues/12)
>     * [ ]  Enable DHT
>       
>       * Overview of issues and why its disabled for now: [ipfs/js-ipfs#1984](https://github.com/ipfs/js-ipfs/issues/1984)
>       * Closest peers query is not efficient: [libp2p/js-libp2p-kad-dht#86](https://github.com/libp2p/js-libp2p-kad-dht/issues/86)
> * [ ]  UI / defaults for storage limits and GC in js-ipfs
>   
>   * js-ipfs does not have GC yet: [ipfs/js-ipfs#2022](https://github.com/ipfs/js-ipfs/pull/2022)
> * [ ]  inspect libp2p connection manager limits
> * [x]  DNS lookups hit `ipfs.io/api/v0/dns`: we need to add cache to this, or support DoH ([ipfs/js-ipfs#2212](https://github.com/ipfs/js-ipfs/issues/2212)) or implement  `chrome.sockets.udp*` API
>   
>   * [x]  Throttling and caching implemented in [ipfs/js-ipfs#2304](https://github.com/ipfs/js-ipfs/pull/2304)

**Comment by lidel** [comment]
Closing this, as we already deprecated this experiment in recent release.

Brave 1.19 shipped with native support for IPFS which leverages go-ipfs instead:

- https://blog.ipfs.io/2021-01-19-ipfs-in-brave/
- https://brave.com/brave-integrates-ipfs/
- https://brave.com/ipfs-support/
